=== jms90h5/Claude-skills/samples/com.teracloud.streams.teda/demo/teda_tutorial/teda.lookupmgr/etc/LookupMgrCustomizing.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- begin_generated_IBM_copyright_prolog                             -->
<!--                                                                  -->
<!-- This is an automatically generated copyright prolog.             -->
<!-- After initializing,  DO NOT MODIFY OR MOVE                       -->
<!-- **************************************************************** -->
<!-- Licensed Materials - Property of IBM                             -->
<!-- 5724-Y95                                                         -->
<!-- (C) Copyright IBM Corp.  2011, 2025    All Rights Reserved.      -->
<!-- US Government Users Restricted Rights - Use, duplication or      -->
<!-- disclosure restricted by GSA ADP Schedule Contract with          -->
<!-- IBM Corp.                                                        -->
<!--                                                                  -->
<!-- end_generated_IBM_copyright_prolog                               -->
<!-- begin_generated_IBM_Teracloud_ApS_copyright_prolog               -->
<!--                                                                  -->
<!-- This is an automatically generated copyright prolog.             -->
<!-- After initializing,  DO NOT MODIFY OR MOVE                       -->
<!-- **************************************************************** -->
<!-- Licensed Materials - Property of IBM                             -->
<!-- (C) Copyright Teracloud ApS 2024, 2025, IBM Corp. 2023, 2023     -->
<!-- All Rights Reserved.                                             -->
<!-- US Government Users Restricted Rights - Use, duplication or      -->
<!-- disclosure restricted by GSA ADP Schedule Contract with          -->
<!-- IBM Corp.                                                        -->
<!--                                                                  -->
<!-- end_generated_IBM_Teracloud_ApS_copyright_prolog                 -->
<xs:schema 
	xmlns="http://www.ibm.com/xmlns/prod/streams/teda" 
	xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.ibm.com/xmlns/prod/streams/teda">
	<xs:element name="LookupManager">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element ref="DataSources"></xs:element>
				<xs:element ref="Segments"></xs:element>
			</xs:sequence>
			<xs:attribute name="SchemaVersion" type="xs:decimal" use="required" fixed="2.0"/>
		</xs:complexType>
		<xs:unique name="UniqueMemSegmtName">
			<xs:selector xpath="Segments/Segment"/>
			<xs:field xpath="@Name"/>
		</xs:unique>
		<xs:unique name="UniqueStreamSchemaName">
			<xs:selector xpath="DataSources/DataSource"/>
			<xs:field xpath="@Name"/>
		</xs:unique>
	</xs:element>
	<xs:element name="Application">
		<xs:annotation>
			<xs:documentation>
				The ITE application defined by application namespace
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="Namespace"
				type="applicationUniqueNameType" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="Applications">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="unbounded">
				<xs:element ref="Application" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Segments">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="unbounded">
				<xs:element ref="Segment" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="DataSources">
		<xs:annotation>
			<xs:documentation>
				Indexing begins with 0
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="DataSource" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Segment">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Stores" maxOccurs="unbounded" />
				<xs:element ref="Applications" maxOccurs="unbounded" minOccurs="1"/>
			</xs:sequence>
			<xs:attribute name="DataSource" use="required" type="spaceLessStringType"/>
			<xs:attribute name="Name" use="required" type="spaceLessStringType"/>
			<xs:attribute name="DataSourceForValueRemoval" use="optional" type="spaceLessStringType"/>
			<xs:attribute name="Unit" type="unitType" use="required"/>
			<xs:attribute name="Size" type="xs:integer" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="DataSource">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ValueDefinition" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="Name" type="spaceLessStringType" use="required"/>
			<xs:attribute name="DbAccessSpecification" type="spaceLessStringType" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Stores">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="unbounded">
				<xs:element ref="Store" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Store">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ValueAssignment" minOccurs="1" maxOccurs="unbounded"/>
				<xs:element ref="KeyAssignment" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="Name" type="spaceLessStringType" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ValueAssignment">
		<xs:complexType>
			<xs:attribute name="SPLType" type="basicSPLTypes" use="required"/>
			<xs:attribute name="Name" type="spaceLessStringType" use="required"/>
			<xs:attribute name="SPLExpression" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="KeyAssignment">
		<xs:complexType>
			<xs:attribute name="SPLType" type="basicSPLTypes" use="required"/>
			<xs:attribute name="SPLExpression" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ValueDefinition">
		<xs:complexType>
			<xs:attribute name="SPLType" type="basicSPLTypes" use="required"/>
			<xs:attribute name="Name" type="spaceLessStringType" use="required"/>
			<xs:attribute name="DbColumnName" type="spaceLessStringType" use="optional"/>
			<xs:attribute name="IndexInInputFile" type="xs:integer" use="optional">
				<xs:annotation>
					<xs:documentation>First element begins with index 0</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="Description" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="applicationUniqueNameType">
		<xs:annotation>
			<xs:documentation>
				The unique name of the application's job
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:minLength value="3"/>
			<xs:pattern value="([a-z0-9_]*\.)*([a-z0-9_]*)"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="unitType">
		<xs:annotation>
			<xs:documentation>
				The memory size unit.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="Byte"/>
			<xs:enumeration value="kB"/>
			<xs:enumeration value="MB"/>
			<xs:enumeration value="GB"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="spaceLessStringType">
		<xs:annotation>
			<xs:documentation>
				Space less string.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:minLength value="3"/>
			<xs:pattern value="[\w\._]*"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="basicSPLTypes">
		<xs:annotation>
			<xs:documentation>Basic SPL types</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="boolean"/>
			<xs:enumeration value="timestamp"/>
			<xs:enumeration value="rstring"/>
			<xs:enumeration value="ustring"/>
			<xs:enumeration value="int8"/>
			<xs:enumeration value="int16"/>
			<xs:enumeration value="int32"/>
			<xs:enumeration value="int64"/>
			<xs:enumeration value="uint8"/>
			<xs:enumeration value="uint16"/>
			<xs:enumeration value="uint32"/>
			<xs:enumeration value="uint64"/>
			<xs:enumeration value="float32"/>
			<xs:enumeration value="float64"/>
			<xs:enumeration value="complex32"/>
			<xs:enumeration value="complex64"/>
			<xs:enumeration value="decimal32"/>
			<xs:enumeration value="decimal64"/>
			<xs:enumeration value="decimal128"/>
			<xs:enumeration value="xml"/>
			<xs:enumeration value="blob"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== jms90h5/Claude-skills/samples/com.teracloud.streams.teda/demo/teda_tutorial/teda.lookupmgr/LookupMgrCustomizing.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- begin_generated_IBM_Teracloud_ApS_copyright_prolog               -->
<!--                                                                  -->
<!-- This is an automatically generated copyright prolog.             -->
<!-- After initializing,  DO NOT MODIFY OR MOVE                       -->
<!-- **************************************************************** -->
<!-- Licensed Materials - Property of IBM                             -->
<!-- (C) Copyright Teracloud ApS 2024, 2025, IBM Corp. 2011, 2015     -->
<!-- All Rights Reserved.                                             -->
<!-- US Government Users Restricted Rights - Use, duplication or      -->
<!-- disclosure restricted by GSA ADP Schedule Contract with          -->
<!-- IBM Corp.                                                        -->
<!--                                                                  -->
<!-- end_generated_IBM_Teracloud_ApS_copyright_prolog                 -->
<LookupManager xmlns="http://www.ibm.com/xmlns/prod/streams/teda" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:teda="http://www.ibm.com/xmlns/prod/streams/teda" SchemaVersion="2.0" xsi:schemaLocation="http://www.ibm.com/xmlns/prod/streams/teda etc/LookupMgrCustomizing.xsd">
  <DataSources>
    <!--Indexing begins with 0-->
    <DataSource Name="IMSI_CRM">
      <ValueDefinition SPLType="rstring" Name="imsi" Description="Lookup key: Subscriber IMSI." IndexInInputFile="0"/>
      <ValueDefinition SPLType="int64" Name="customerId" Description="Lookup result: customerId." IndexInInputFile="1"/>
      <ValueDefinition SPLType="int64" Name="customerType" Description="Lookup result: customerType." IndexInInputFile="2"/>
    </DataSource>
  </DataSources>
  <Segments>
    <Segment Name="segmentDemoApp" DataSource="IMSI_CRM" Size="1200" Unit="MB">
      <Stores>
        <Store Name="ImsiMap">
          <ValueAssignment SPLType="int64" Name="customerId" SPLExpression="customerId"/>
          <ValueAssignment SPLType="int64" Name="customerType" SPLExpression="customerType"/>
          <KeyAssignment SPLType="rstring" SPLExpression="(rstring)imsi"/>
        </Store>
      </Stores>
      <Applications>
        <Application Namespace="demoapp"/>
      </Applications>
    </Segment>
  </Segments>
</LookupManager>
